Feat/update products #34
hngprojects/hng_boilerplate_php_laravel_web pull request #163
Opened 2024-07-24 20:48 UTC by Taiwola

Update Product
​
## Description

This endpoint allows updating the details of a product item. It accepts various product attributes and updates the corresponding fields in the database, including the updated_at timestamp to reflect the time of the update.
​
## Related Issue (Link to Github issue)

The use of make in the product factory resulted in the creation of a user instance that was not persisted in the database. This caused problems during the seeding process where product creation failed due to missing user references.

### **Steps to Reproduce**
Run the database seeder to seed the products.
Observe the foreign key constraint violation error related to the user reference.

### **Solution**
The fix involves replacing the make function with the create function in the product factory to ensure that the user instance is properly persisted in the database.

Update product issue: https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/34
​
## How Has This Been Tested?

I used Thunder Client to test each endpoint to ensure that the code works as expected without any issues.

Testing Environment:

> Local development server
> Thunder Client extension in Visual Studio Code

### **Tests Run**

1. Update Product with Valid Data:

-               Sent a PUT request to /api/v1/products/{id} with valid product data.
-               Verified that the product was updated successfully and received a 200 OK response with the updated product details.

2. Update Product with Missing Fields:

-                 Sent a PUT request to /api/v1/products/{id} with only some of the fields provided.
-                     Verified that only the provided fields were updated and received a 200 OK response with the updated product details.

3. Update Non-Existent Product:

-                  Sent a PUT request to /api/v1/products/nonexistent-id to test the response for a non-existent product.
-                  Verified that the response was a 404 Not Found with an appropriate error message.

4, Update Product with Missing Authentication:

-            Sent a PUT request to /api/v1/products/{id} without authentication headers.

-                 Verified that the response was a 401 Unauthorized.

​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-07-24 20:54 UTC, Taiwola commented
@onyx093 
@Goldengide 
@tulbadex 
@bhimbho 

pls review

2024-07-24 21:03 UTC, Taiwola commented
@Dev-Tonia 
@Muhammad235

2024-07-24 21:21 UTC, Dev-Tonia approved these changes
You fixed a bug not a new feature,
Rename to fix

2024-07-24 21:27 UTC, Dev-Tonia reviewed
Rename to bug fix

2024-07-24 21:32 UTC, timiajayi commented
add link to github issue

2024-07-24 21:35 UTC, Taiwola commented
okk.....

2024-07-24 21:40 UTC, Taiwola commented
i have updated it @timiajayi

2024-07-25 08:33 UTC, Taiwola commented
@Ruthiejayjay

2024-07-25 09:45 UTC, Taiwola commented
@Ruthiejayjay

2024-07-25 21:51 UTC, Goldengide commented
> @onyx093 @Goldengide @tulbadex @bhimbho
> 
> pls review

Bro, I don't have the power to review I noticed you have some pulling and merge conflicts to solve though

2024-07-25 22:13 UTC, bhimbho requested changes

2024-07-25 22:13 UTC, bhimbho commented on tests/Feature/BlogSearchTest.php
why is this test file removed? this is a test written by @timiajayi for his work done on Blog search endpoint

2024-07-25 22:13 UTC, bhimbho commented on tests/Feature/BlogSearchTest.php
also merge conflicts

2024-07-28 19:00 UTC, closed without merging