Add product endpoint
hngprojects/hng_boilerplate_php_laravel_web pull request #99
Opened 2024-07-22 09:50 UTC by Muhammad235

​
## Description

​
## Related Issue (Link to Github issue)
This PR is related to the issue [here](https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/3)
​
## Motivation and Context
This endpoint permit the creation of products by users 
​
## How Has This Been Tested?
A unit test was carried out on this endpoint with full coverage
​
## Screenshots (if appropriate - Postman, etc):
![Screenshot (120)](https://github.com/user-attachments/assets/658614b9-008a-4554-a6d3-82baa6cbc56a)
​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

2024-07-22 10:16 UTC, ruxy1212 approved these changes

2024-07-22 10:21 UTC, ruxy1212 requested changes
Please reformat your response, it's message, status_code, data. Data will contain the newly created object

2024-07-22 10:34 UTC, ruxy1212 approved these changes

2024-07-23 17:13 UTC, Ruthiejayjay approved these changes

2024-07-23 17:13 UTC, merged